import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { assertBrandAccess } from '$lib/server/marketplace/brandAuth';
import { env } from '$env/dynamic/private';
import { logTaste } from '$lib/server/creative/contextBuilder';

export const POST: RequestHandler = async ({ request }) => {
  const igUserId = assertBrandAccess(request);
  if (!igUserId) throw error(401, 'Brand IG session required');

  const body = await request.json();
  const { generationId, version, sendToScheduler } = body as {
    generationId: string;
    version: number;
    sendToScheduler: boolean;
  };

  const supabaseUrl = env.SUPABASE_URL!;
  const headers = { apikey: env.SUPABASE_SERVICE_ROLE_KEY!, Authorization: `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`, 'Content-Type': 'application/json' };

  // Get the approved version
  const verRes = await fetch(`${supabaseUrl}/rest/v1/creative_generation_versions?generation_id=eq.${generationId}&version=eq.${version}&limit=1`, { headers });
  const vers = await verRes.json();
  if (!vers.length) throw error(404, 'Version not found');
  const approvedVer = vers[0];

  // Mark generation as approved
  await fetch(`${supabaseUrl}/rest/v1/creative_generations?id=eq.${generationId}`, {
    method: 'PATCH',
    headers,
    body: JSON.stringify({
      status: 'approved',
      approved_version: version,
      approved_at: new Date().toISOString(),
    }),
  });

  await logTaste(igUserId, generationId, 'approval', { version, sendToScheduler });

  let scheduledPostId = null;
  if (sendToScheduler && approvedVer.image_gcs_url) {
    // Send to Module 1 scheduler
    const copyPayload = approvedVer.copy_payload || {};
    const scheduleRes = await fetch(`${supabaseUrl}/rest/v1/scheduled_posts`, {
      method: 'POST',
      headers: { ...headers, Prefer: 'return=representation' },
      body: JSON.stringify({
        brand_ig_id: igUserId,
        gcs_url: approvedVer.image_gcs_url,
        media_type: 'IMAGE',
        caption: copyPayload.caption || '',
        hashtags: copyPayload.hashtags || [],
        alt_text: '',
        status: 'draft',
        ai_reasoning: `Generated by AI Creative Studio, generation ${generationId} v${version}`,
      }),
    });
    if (scheduleRes.ok) {
      const [post] = await scheduleRes.json();
      scheduledPostId = post.id;
    }
  }

  return json({
    ok: true,
    gcsUrl: approvedVer.image_gcs_url,
    scheduledPostId,
    schedulerStatus: scheduledPostId ? 'draft' : 'not_sent',
  });
};
