-- Intentionally left non-destructive.
--
-- This filename was originally used for a local fresh-start reset script. Keeping
-- DROP TABLE statements in supabase/migrations makes automated migration runners
-- delete production tables when they apply pending migrations. The manual reset
-- SQL now lives in:
--
--   supabase/manual-reset/20260509000000_drop_unused_tables.sql
