-- Intentionally left non-destructive.
--
-- This filename was originally used for a local fresh-start reset script. Keeping
-- destructive TRUNCATE statements in supabase/migrations makes automated
-- migration runners wipe every production table when they apply pending
-- migrations. The manual reset SQL now lives in:
--
--   supabase/manual-reset/20260509000001_truncate_all_data.sql
