-- ============================================
-- INTENTIONALLY EMPTY
-- ============================================
-- This file used to wipe core production tables. Destructive reset
-- operations must not live in supabase/migrations because standard Supabase
-- migration tooling applies this directory automatically. Keep this timestamp
-- as a no-op so applying migrations cannot wipe user, campaign, chat, or
-- earnings data.
