-- ============================================
-- INTENTIONALLY EMPTY
-- ============================================
-- This migration previously dropped tables that still have live application
-- readers/writers (creative studio, content activity, carousel items, and
-- brand intelligence tables). Leaving this timestamp as a no-op prevents
-- accidental data loss while preserving migration ordering for environments
-- that have already seen the filename.
